### ISSUE TITLE
Mod Crashing After Recent Update 

### ISSUE THREAD

**Issue by abordoli** [sullerandras/UtilizationMonitor#17]
Mod Crashing After Recent Update 
Bordo - 12 hours ago   Edit 

Gives a runtime error quite frequently and crashes to menu losing all unsaved work.
I'll report back with the specific error script next time it happens.

Bordo - now   Edit 

Here is the exact error and happens when an entity that is being monitored is deleted:
 "
 Notice
 Error while running event
 UtilizationMonitor:on_tick(ID o)
 _UtilizationMonitor _/control.lua:453:
 attempt to index local 'data' (a nil value)
 "

**Comment by ST-DDT** [comment]
I cannot reproduce that issue locally. But I have a guess on how to fix it.

Could you please try out this fix and report whether it works?

Replace [control.lua#442](https://github.com/sullerandras/UtilizationMonitor/blob/master/control.lua#L442)

````lua
 if id then
    data = entity_data[id]
  else
    id, data = next(entity_data, nil)
  end
````

with:

````lua
if id then
    data = entity_data[id]
    if data == nil then
      id, data = next(entity_data, nil)
    end
  else
    id, data = next(entity_data, nil)
  end
````

If it does not work could you explain how to reproduce that error?

**Comment by abordoli** [comment]
I will try the fix and report back...

**Comment by sullerandras** [comment]
If the line number is correct, it is failing on this line:
https://github.com/sullerandras/UtilizationMonitor/blob/05cad7c3ce0551a335ca66a6d1dead4b2f812003/control.lua#L453
My first idea would be to add a `data != nil` here, something like this:
```lua
if data != nil and data.entity.valid then
```
Would that work?
