### ISSUE TITLE
0.16?

### ISSUE THREAD

**Issue by abordoli** [sullerandras/UtilizationMonitor#2]
Would be much appreciated as this, along with Bottleneck, is a mod that I can't play without.
Regards,
~B

**Comment by sullerandras** [comment]
I can look into this early next year. Pull requests are welcome if someone willing to fix whatever is broken :)

On 26 December 2017 17:02:17 GMT+07:00, abordoli <notifications@github.com> wrote:
>Would be much appreciated as this, along with Bottleneck, is a mod that
>I can't play without.
>Regards,
>~B
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sullerandras/UtilizationMonitor/issues/2

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sullerandras** [comment]
Updated it. Let me know if it doesn't work for you.

**Comment by abordoli** [comment]
Tested and works as expected. Thanks again!
